#!/usr/bin/env python3
"""
generate_trainer.py — emit a complete nfsmw_trainer.c from a patch list.

Given one or more (address, kind, value) tuples, produce a self-contained
C source file that, when built as an ASI, applies the patches to a running
speed.exe (NFSMW). Mirrors the style of mods/infinite_trainer/nfsmw_trainer.c.

Usage:
    generate_trainer.py --out trainer.c \
        --patch 0x937804:byte:1 \
        --patch 0x988E1C:byte:1 \
        --patch 0x901B1C:float:2.0

Each --patch is "<addr>:<kind>:<value>" where kind is byte|word|int|float.
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path
from typing import NamedTuple


class Patch(NamedTuple):
    addr: int
    kind: str   # byte | word | int | float
    value: str  # raw token, type-cast at emit time


def parse_patch(token: str) -> Patch:
    parts = token.split(":")
    if len(parts) != 3:
        raise ValueError(f"--patch expects addr:kind:value, got {token!r}")
    addr_s, kind, value = parts
    kind = kind.lower()
    if kind not in ("byte", "word", "int", "float"):
        raise ValueError(f"unknown kind {kind!r}; want byte|word|int|float")
    addr = int(addr_s, 0)
    if not (0x00400000 <= addr < 0x01000000):
        # NFSMW image is mapped 0x00400000..~0x00B00000; warn rather than fail
        print(f"warning: addr {addr:#x} outside typical speed.exe range",
              file=sys.stderr)
    # Validate the value parses for the declared kind
    if kind == "float":
        float(value)
    else:
        v = int(value, 0)
        max_bits = {"byte": 8, "word": 16, "int": 32}[kind]
        if not (0 <= v < (1 << max_bits)) and not (-(1 << (max_bits - 1)) <= v < (1 << max_bits)):
            raise ValueError(f"value {v} doesn't fit in {kind}")
    return Patch(addr, kind, value)


def emit_patch_line(p: Patch) -> str:
    if p.kind == "byte":
        return f'    write_byte(0x{p.addr:08X}u, (BYTE)({p.value}));'
    if p.kind == "word":
        return f'    write_word(0x{p.addr:08X}u, (WORD)({p.value}));'
    if p.kind == "int":
        return f'    write_int (0x{p.addr:08X}u, (DWORD)({p.value}));'
    if p.kind == "float":
        # Pre-compute the IEEE-754 bit pattern so the C compiler can't
        # silently re-interpret the literal.
        bits = struct.unpack("<I", struct.pack("<f", float(p.value)))[0]
        return (f'    {{ union {{ float f; DWORD u; }} _v; _v.u = 0x{bits:08X}u;'
                f' write_float(0x{p.addr:08X}u, _v.f); }}  /* {p.value}f */')
    raise AssertionError(p.kind)


TEMPLATE = '''\
/*
 * NFSMW Trainer (auto-generated by tools/nfsmw-tool/generate_trainer.py)
 *
 * Patches applied:
{patch_comments}
 *
 * Build:   make             (in mods/infinite_trainer/)
 * Install: cp *.asi app/scripts/
 */

#include <windows.h>
#include <stdio.h>
#include <stdint.h>

static void write_byte(uintptr_t a, BYTE v) {{
    DWORD o; if (VirtualProtect((LPVOID)a, 1, PAGE_EXECUTE_READWRITE, &o)) {{
        *(BYTE*)a = v; VirtualProtect((LPVOID)a, 1, o, &o); }}
}}
static void write_word(uintptr_t a, WORD v) {{
    DWORD o; if (VirtualProtect((LPVOID)a, 2, PAGE_EXECUTE_READWRITE, &o)) {{
        *(WORD*)a = v; VirtualProtect((LPVOID)a, 2, o, &o); }}
}}
static void write_int(uintptr_t a, DWORD v) {{
    DWORD o; if (VirtualProtect((LPVOID)a, 4, PAGE_EXECUTE_READWRITE, &o)) {{
        *(DWORD*)a = v; VirtualProtect((LPVOID)a, 4, o, &o); }}
}}
static void write_float(uintptr_t a, float v) {{
    DWORD o; if (VirtualProtect((LPVOID)a, 4, PAGE_EXECUTE_READWRITE, &o)) {{
        *(float*)a = v; VirtualProtect((LPVOID)a, 4, o, &o); }}
}}

static int validate_speed_exe(void) {{
    HMODULE m = GetModuleHandleA(NULL);
    if (!m) return 0;
    DWORD nt = *(DWORD*)((BYTE*)m + 0x3C);
    DWORD base = *(DWORD*)((BYTE*)m + nt + 0x34);
    return base == 0x00400000;
}}

static DWORD WINAPI trainer_thread(LPVOID lpv) {{
    (void)lpv;
    Sleep(2000);
    if (!validate_speed_exe()) {{
        OutputDebugStringA("[NFSMW Trainer] not speed.exe; refusing patch\\n");
        return 1;
    }}

{patch_lines}

    OutputDebugStringA("[NFSMW Trainer] {count} patch(es) applied\\n");
    return 0;
}}

BOOL WINAPI DllMain(HINSTANCE hinst, DWORD reason, LPVOID r) {{
    (void)r;
    if (reason == DLL_PROCESS_ATTACH) {{
        DisableThreadLibraryCalls(hinst);
        HANDLE h = CreateThread(NULL, 0, trainer_thread, NULL, 0, NULL);
        if (h) CloseHandle(h);
    }}
    return TRUE;
}}
'''


def render(patches: list[Patch]) -> str:
    patch_comments = "\n".join(
        f' *   - 0x{p.addr:08X} ({p.kind}) <- {p.value}' for p in patches
    )
    patch_lines = "\n".join(emit_patch_line(p) for p in patches)
    return TEMPLATE.format(
        patch_comments=patch_comments,
        patch_lines=patch_lines,
        count=len(patches),
    )


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", "-o", required=True,
                    help="output .c path (e.g. mods/infinite_trainer/nfsmw_trainer.c)")
    ap.add_argument("--patch", "-p", action="append", default=[], required=True,
                    metavar="ADDR:KIND:VALUE",
                    help="patch tuple; kind is byte|word|int|float. Repeatable.")
    args = ap.parse_args(argv)
    patches = [parse_patch(t) for t in args.patch]
    src = render(patches)
    Path(args.out).write_text(src, encoding="utf-8")
    print(f"wrote {args.out} ({len(patches)} patch(es), {len(src)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
